### ISSUE TITLE
Frontend backend interaction

### ISSUE THREAD

**Issue by willirath** [ESM-VFC/ESM-VFC#4]
ToDos:

- [x] Try and see if we can provide a thin `pywps` wrapper around a lazy Xarray / Dask dataset so that we can provide the frontend with an easy-to-use data source.

- [x] Provide a Docker image that just serves an Xarray dataset forever for @alirezamdv to play with for implementing zarr reading directly in the frontend.

**Comment by willirath** [comment]
@alirezamdv See https://github.com/ESM-VFC/xpublish-standalone-demo for a standalone server.

**Comment by benbovy** [comment]
> Try and see if we can provide a thin pywps wrapper around a lazy Xarray / Dask dataset so that we can provide the frontend with an easy-to-use data source.

Alternatively, if we don't need a WPS service and just want tight integration between the backend and frontend, we might provide a more lightweight API endpoint based on a simple Flask+geojson wrapper. See https://github.com/ESM-VFC/ESM-VFC/issues/5#issuecomment-634532996.

**Comment by willirath** [comment]
@alirezamdv Did you have a chance to look at <https://github.com/ESM-VFC/esm-vfc-api-demo>?

**Comment by willirath** [comment]
Closing here as the discussion continues in the API demo repo.
