### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by benbovy** [ESM-VFC/ESM-VFC#5]
Although it has been discussed many times during the previous meetings, sometimes I'm still a bit confused about how would look the VFC application, i.e., which kind of data should be available, in which form, for whom, for what purpose, etc.

I think it would help a lot if we could write down and prioritize some user stories, here or elsewhere. There are good examples of user stories in [this blog post](https://medium.com/informatics-lab/what-do-we-want-from-a-dream-data-platform-as-a-service-c38558c25f29) for general-purpose data platforms.

Applied to this project, one naive example could be:

As a *biologist*, I want to *extract time-series of NEMO outputs at the nearest grid node of a point-location of a ship track*, so that *I can compare it to observational data*.

**Comment by willirath** [comment]
I like this idea. I'll add a few stories later.

**Comment by benbovy** [comment]
Another example:

- As a *scientist (non-modeller)*, I want to *query and visualize model data from within my favorite GIS client/desktop application*, so that *I can work efficiently and keep using the tools that I'm already familiar with*.

I think this specific example illustrates well the importance of user stories in choosing the best options among existing solutions for the architecture and the implementation.

If we want to support this case, then providing a OGC-compliant service (e.g., using PyWPS) makes perfect sense.

But if we don't care much about this use case and we only need tight integration between the backend and the frontend, then I feel that OGC tools like PyWPS (powerful, but quite bloated IMO) may be overkill and a more lightweight, in-house solution (e.g., Flask+geojson) might be easier to build and maintain.

**Comment by willirath** [comment]
Where should we keep the user stories? Here in a markdown doc?

**Comment by benbovy** [comment]
> Where should we keep the user stories? Here in a markdown doc?

Good idea!

**Comment by willirath** [comment]
Done with f564782.
